kind: Deployment
apiVersion: apps/v1
metadata:
  name: dydx-testnet-proposal-atomfeed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dydx-testnet-proposal-atomfeed
  template:
    metadata:
      labels:
        app: dydx-testnet-proposal-atomfeed
    spec:
      containers:
      - args:
        image: derorisan/dydx-testnet-proposal-atomfeed
        imagePullPolicy: Always
        name: dydx-testnet-proposal-atomfeed
        ports:
        - containerPort: 4000
          protocol: TCP
        env:
        - name: PROPS_ENDPOINT
          value: https://dydx-testnet-api.polkachu.com/cosmos/gov/v1/proposals?proposal_status=PROPOSAL_STATUS_UNSPECIFIED&pagination.limit=10&pagination.reverse=true
        - name: LINK_BASE_URL
          value: https://mintscan.io/dydx-testnet/proposals/
---
kind: Service
apiVersion: v1
metadata:
  name: dydx-testnet-proposal-atomfeed
spec:
  ports:
  - name: "http-port"
    protocol: TCP
    port: 80
    targetPort: 4000
  selector:
    app: dydx-testnet-proposal-atomfeed
---
